ext.moduleName = 'event.logging.base'

import java.time.ZonedDateTime
import java.time.format.DateTimeFormatter

// In this section you declare the dependencies for your production and test code
dependencies {
    implementation project(':event-logging-api')

    // The production code uses the SLF4J logging API at compile time
    implementation libs.jaxb_api
    implementation libs.slf4j_api
    runtimeOnly libs.jaxb_impl

    testImplementation(platform(libs.junit_bom))
    testImplementation libs.junit_jupiter_api
    testImplementation libs.junit_jupiter_params
    testImplementation libs.assertj_core
    testImplementation libs.mockito_core

    testRuntimeOnly libs.junit_jupiter_engine
    testRuntimeOnly libs.junit_platform_launcher
    testRuntimeOnly libs.logback_classic
    testRuntimeOnly libs.logback_core
}

// Write a build.properties file that will be gitignored and will go in the jar
// for the BuildInfo class to read at runtime.
tasks.register('writeBuildProperties') {
    def propertyFile = file "${project.rootDir}/event-logging-base/src/main/resources/META-INF/build.properties"
    propertyFile.parentFile.mkdirs()
    def props = new Properties()

    props.setProperty("schemaVersion", project.eventLoggingSchemaVer)
    props.setProperty("buildVersion", project.projectVersion)
    props.setProperty("buildDate", ZonedDateTime.now().format(DateTimeFormatter.ISO_INSTANT))

    props.store(propertyFile.newWriter(), null)
}

// Ensure the build.properties file is present when the resources are
// added to the jar
tasks.processResources.dependsOn writeBuildProperties


