var event_logging_Module_Factory = function () {
  var event_logging = {
    name: 'event_logging',
    defaultElementNamespaceURI: 'event-logging:3',
    typeInfos: [{
        localName: 'GroupChat',
        baseTypeInfo: '.BaseChat'
      }, {
        localName: 'NetworkEventAction',
        propertyInfos: [{
            name: 'bind',
            required: true,
            elementName: 'Bind',
            typeInfo: '.NetworkOutcome'
          }, {
            name: 'connect',
            required: true,
            elementName: 'Connect',
            typeInfo: '.NetworkOutcome'
          }, {
            name: 'open',
            required: true,
            elementName: 'Open',
            typeInfo: '.NetworkOutcome'
          }, {
            name: 'close',
            required: true,
            elementName: 'Close',
            typeInfo: '.NetworkOutcome'
          }, {
            name: 'send',
            required: true,
            elementName: 'Send',
            typeInfo: '.NetworkOutcome'
          }, {
            name: 'receive',
            required: true,
            elementName: 'Receive',
            typeInfo: '.NetworkOutcome'
          }, {
            name: 'listen',
            required: true,
            elementName: 'Listen',
            typeInfo: '.NetworkOutcome'
          }, {
            name: 'permit',
            required: true,
            elementName: 'Permit',
            typeInfo: '.NetworkOutcome'
          }, {
            name: 'deny',
            required: true,
            elementName: 'Deny',
            typeInfo: '.NetworkOutcome'
          }]
      }, {
        localName: 'Approval',
        propertyInfos: [{
            name: 'action',
            required: true,
            elementName: 'Action',
            typeInfo: '.ApprovalAction'
          }, {
            name: 'id',
            elementName: 'Id'
          }, {
            name: 'subject',
            elementName: 'Subject',
            typeInfo: '.MultiObject'
          }, {
            name: 'requestors',
            elementName: 'Requestors',
            typeInfo: '.Approval.Requestors'
          }, {
            name: 'approvers',
            elementName: 'Approvers',
            typeInfo: '.Approval.Approvers'
          }, {
            name: 'reason',
            elementName: 'Reason'
          }, {
            name: 'outcome',
            elementName: 'Outcome',
            typeInfo: '.Outcome'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Network',
        baseTypeInfo: '.BaseNetwork'
      }, {
        localName: 'Install',
        propertyInfos: [{
            name: 'software',
            required: true,
            elementName: 'Software',
            typeInfo: '.Software'
          }, {
            name: 'hardware',
            required: true,
            elementName: 'Hardware',
            typeInfo: '.Hardware'
          }, {
            name: 'media',
            required: true,
            elementName: 'Media',
            typeInfo: '.Media'
          }, {
            name: 'outcome',
            elementName: 'Outcome',
            typeInfo: '.Outcome'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Approval.Requestors',
        typeName: null,
        propertyInfos: [{
            name: 'requestor',
            required: true,
            collection: true,
            elementName: 'Requestor',
            typeInfo: '.User'
          }]
      }, {
        localName: 'BaseOutcome.AuthService',
        typeName: null,
        propertyInfos: [{
            name: 'id',
            elementName: 'Id'
          }, {
            name: 'cacheTimeout',
            elementName: 'CacheTimeout',
            typeInfo: 'PositiveInteger'
          }]
      }, {
        localName: 'Create',
        baseTypeInfo: '.BaseObjectOutcome'
      }, {
        localName: 'MultiObject',
        propertyInfos: [{
            name: 'multiObjectGroup',
            required: true,
            collection: true,
            elementTypeInfos: [{
                elementName: 'Association',
                typeInfo: '.Association'
              }, {
                elementName: 'Banner',
                typeInfo: '.Banner'
              }, {
                elementName: 'Chat',
                typeInfo: '.Chat'
              }, {
                elementName: 'Configuration',
                typeInfo: '.Configuration'
              }, {
                elementName: 'Criteria',
                typeInfo: '.Criteria'
              }, {
                elementName: 'Document',
                typeInfo: '.Document'
              }, {
                elementName: 'Email',
                typeInfo: '.Email'
              }, {
                elementName: 'File',
                typeInfo: '.File'
              }, {
                elementName: 'Folder',
                typeInfo: '.Folder'
              }, {
                elementName: 'Group',
                typeInfo: '.Group'
              }, {
                elementName: 'GroupChat',
                typeInfo: '.GroupChat'
              }, {
                elementName: 'Object',
                typeInfo: '.Object'
              }, {
                elementName: 'SearchResults',
                typeInfo: '.SearchResults'
              }, {
                elementName: 'Shortcut',
                typeInfo: '.Shortcut'
              }, {
                elementName: 'User',
                typeInfo: '.User'
              }, {
                elementName: 'VirtualSession',
                typeInfo: '.VirtualSession'
              }, {
                elementName: 'VOIP',
                typeInfo: '.VOIP'
              }, {
                elementName: 'Resource',
                typeInfo: '.Resource'
              }],
            type: 'elements'
          }]
      }, {
        localName: 'Classification.PermittedNationalities',
        typeName: null,
        propertyInfos: [{
            name: 'nationality',
            required: true,
            collection: true,
            elementName: 'Nationality'
          }]
      }, {
        localName: 'Authorise.RemoveGroups',
        typeName: null,
        propertyInfos: [{
            name: 'group',
            minOccurs: 0,
            collection: true,
            elementName: 'Group',
            typeInfo: '.Group'
          }]
      }, {
        localName: 'Configuration',
        baseTypeInfo: '.BaseObject',
        propertyInfos: [{
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'BaseOutcome',
        propertyInfos: [{
            name: 'success',
            elementName: 'Success',
            typeInfo: 'Boolean'
          }, {
            name: 'permitted',
            elementName: 'Permitted',
            typeInfo: 'Boolean'
          }, {
            name: 'authService',
            elementName: 'AuthService',
            typeInfo: '.BaseOutcome.AuthService'
          }, {
            name: 'description',
            elementName: 'Description'
          }]
      }, {
        localName: 'Event',
        typeName: null,
        propertyInfos: [{
            name: 'meta',
            minOccurs: 0,
            collection: true,
            elementName: 'Meta',
            typeInfo: '.AnyContent'
          }, {
            name: 'classification',
            elementName: 'Classification',
            typeInfo: '.Classification'
          }, {
            name: 'eventTime',
            required: true,
            elementName: 'EventTime',
            typeInfo: '.EventTime'
          }, {
            name: 'eventSource',
            required: true,
            elementName: 'EventSource',
            typeInfo: '.EventSource'
          }, {
            name: 'eventDetail',
            required: true,
            elementName: 'EventDetail',
            typeInfo: '.EventDetail'
          }, {
            name: 'eventChain',
            elementName: 'EventChain',
            typeInfo: '.EventChain'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Or',
        propertyInfos: [{
            name: 'advancedQueryOperatorGroup',
            minOccurs: 0,
            collection: true,
            elementTypeInfos: [{
                elementName: 'Term',
                typeInfo: '.Term'
              }, {
                elementName: 'And',
                typeInfo: '.And'
              }, {
                elementName: 'Or',
                typeInfo: '.Or'
              }, {
                elementName: 'Not',
                typeInfo: '.Not'
              }],
            type: 'elements'
          }]
      }, {
        localName: 'Move',
        propertyInfos: [{
            name: 'source',
            required: true,
            elementName: 'Source',
            typeInfo: '.MultiObject'
          }, {
            name: 'destination',
            required: true,
            elementName: 'Destination',
            typeInfo: '.MultiObject'
          }, {
            name: 'outcome',
            elementName: 'Outcome',
            typeInfo: '.CopyMoveOutcome'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Hardware',
        propertyInfos: [{
            name: 'type',
            required: true,
            elementName: 'Type',
            typeInfo: '.HardwareType'
          }, {
            name: 'id',
            elementName: 'Id'
          }, {
            name: 'name',
            elementName: 'Name'
          }, {
            name: 'model',
            elementName: 'Model'
          }, {
            name: 'manufacturer',
            elementName: 'Manufacturer'
          }, {
            name: 'capacity',
            elementName: 'Capacity',
            typeInfo: 'PositiveInteger'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'View',
        baseTypeInfo: '.BaseObjectOutcome'
      }, {
        localName: 'Criteria',
        baseTypeInfo: '.BaseObject',
        propertyInfos: [{
            name: 'dataSources',
            elementName: 'DataSources',
            typeInfo: '.SearchResults.DataSources'
          }, {
            name: 'query',
            elementName: 'Query',
            typeInfo: '.Query'
          }, {
            name: 'resultPage',
            elementName: 'ResultPage',
            typeInfo: '.SearchResults.ResultPage'
          }, {
            name: 'totalResults',
            elementName: 'TotalResults',
            typeInfo: 'NonNegativeInteger'
          }, {
            name: 'results',
            elementName: 'Results',
            typeInfo: '.MultiObject'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Activity',
        propertyInfos: [{
            name: 'id',
            required: true,
            elementName: 'Id'
          }, {
            name: 'name',
            elementName: 'Name'
          }, {
            name: 'parent',
            elementName: 'Parent',
            typeInfo: '.Activity'
          }]
      }, {
        localName: 'Classification',
        propertyInfos: [{
            name: 'text',
            elementName: 'Text'
          }, {
            name: 'originator',
            elementName: 'Originator',
            typeInfo: '.Organisation'
          }, {
            name: 'custodian',
            elementName: 'Custodian',
            typeInfo: '.Organisation'
          }, {
            name: 'classification',
            elementName: 'Classification'
          }, {
            name: 'descriptors',
            elementName: 'Descriptors',
            typeInfo: '.Classification.Descriptors'
          }, {
            name: 'orGroups',
            elementName: 'OrGroups',
            typeInfo: '.AccessControlGroups'
          }, {
            name: 'andGroups',
            elementName: 'AndGroups',
            typeInfo: '.AccessControlGroups'
          }, {
            name: 'permittedNationalities',
            elementName: 'PermittedNationalities',
            typeInfo: '.Classification.PermittedNationalities'
          }, {
            name: 'permittedOrganisations',
            elementName: 'PermittedOrganisations',
            typeInfo: '.Classification.PermittedOrganisations'
          }, {
            name: 'disseminationControls',
            elementName: 'DisseminationControls',
            typeInfo: '.Classification.DisseminationControls'
          }, {
            name: 'disposition',
            elementName: 'Disposition',
            typeInfo: '.Classification.Disposition'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Delete',
        baseTypeInfo: '.BaseObjectOutcome'
      }, {
        localName: 'AuthenticateOutcome',
        baseTypeInfo: '.BaseOutcome',
        propertyInfos: [{
            name: 'reason',
            elementName: 'Reason',
            typeInfo: '.AuthenticateOutcomeReason'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Classification.PermittedOrganisations',
        typeName: null,
        propertyInfos: [{
            name: 'permittedOrganisation',
            required: true,
            elementName: 'PermittedOrganisation',
            typeInfo: '.Organisation'
          }]
      }, {
        localName: 'Email',
        baseTypeInfo: '.BaseObject',
        propertyInfos: [{
            name: 'from',
            elementName: 'From',
            typeInfo: '.User'
          }, {
            name: 'to',
            minOccurs: 0,
            collection: true,
            elementName: 'To',
            typeInfo: '.User'
          }, {
            name: 'cc',
            minOccurs: 0,
            collection: true,
            elementName: 'Cc',
            typeInfo: '.User'
          }, {
            name: 'bcc',
            minOccurs: 0,
            collection: true,
            elementName: 'Bcc',
            typeInfo: '.User'
          }, {
            name: 'subject',
            elementName: 'Subject'
          }, {
            name: 'content',
            elementName: 'Content'
          }, {
            name: 'mimeType',
            elementName: 'MimeType'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Location',
        propertyInfos: [{
            name: 'country',
            elementName: 'Country'
          }, {
            name: 'state',
            elementName: 'State'
          }, {
            name: 'city',
            elementName: 'City'
          }, {
            name: 'town',
            elementName: 'Town'
          }, {
            name: 'site',
            elementName: 'Site'
          }, {
            name: 'building',
            elementName: 'Building'
          }, {
            name: 'floor',
            elementName: 'Floor',
            typeInfo: 'Integer'
          }, {
            name: 'room',
            elementName: 'Room'
          }, {
            name: 'desk',
            elementName: 'Desk'
          }, {
            name: 'rack',
            elementName: 'Rack'
          }, {
            name: 'position',
            elementName: 'Position'
          }, {
            name: 'timeZoneName',
            elementName: 'TimeZoneName'
          }, {
            name: 'coordinates',
            elementName: 'Coordinates',
            typeInfo: '.Coordinates'
          }, {
            name: 'accessZone',
            elementName: 'AccessZone'
          }]
      }, {
        localName: 'MetaDataTags',
        propertyInfos: [{
            name: 'tag',
            required: true,
            collection: true,
            elementName: 'Tag'
          }]
      }, {
        localName: 'AntiMalwareThreat.Signature',
        typeName: null,
        propertyInfos: [{
            name: 'version',
            elementName: 'Version'
          }, {
            name: 'updated',
            elementName: 'Updated',
            typeInfo: 'DateTime'
          }]
      }, {
        localName: 'BaseObject',
        propertyInfos: [{
            name: 'meta',
            minOccurs: 0,
            collection: true,
            elementName: 'Meta',
            typeInfo: '.AnyContent'
          }, {
            name: 'type',
            elementName: 'Type'
          }, {
            name: 'id',
            elementName: 'Id'
          }, {
            name: 'name',
            elementName: 'Name'
          }, {
            name: 'description',
            elementName: 'Description'
          }, {
            name: 'classification',
            elementName: 'Classification',
            typeInfo: '.Classification'
          }, {
            name: 'state',
            elementName: 'State'
          }, {
            name: 'groups',
            elementName: 'Groups',
            typeInfo: '.Groups'
          }, {
            name: 'permissions',
            elementName: 'Permissions',
            typeInfo: '.BaseObject.Permissions'
          }, {
            name: 'tags',
            elementName: 'Tags',
            typeInfo: '.MetaDataTags'
          }]
      }, {
        localName: 'Hash',
        propertyInfos: [{
            name: 'value',
            type: 'value'
          }, {
            name: 'type',
            attributeName: {
              localPart: 'Type'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'Alert.Change',
        typeName: null,
        propertyInfos: [{
            name: 'action',
            required: true,
            elementName: 'Action',
            typeInfo: '.ChangeAction'
          }, {
            name: 'before',
            elementName: 'Before',
            typeInfo: '.MultiObject'
          }, {
            name: 'after',
            elementName: 'After',
            typeInfo: '.MultiObject'
          }, {
            name: 'rule',
            elementName: 'Rule'
          }]
      }, {
        localName: 'Term',
        propertyInfos: [{
            name: 'name',
            required: true,
            elementName: 'Name'
          }, {
            name: 'condition',
            required: true,
            elementName: 'Condition',
            typeInfo: '.TermCondition'
          }, {
            name: 'value',
            required: true,
            elementName: 'Value'
          }]
      }, {
        localName: 'Query.Simple',
        typeName: null,
        propertyInfos: [{
            name: 'include',
            elementName: 'Include'
          }, {
            name: 'exclude',
            elementName: 'Exclude'
          }]
      }, {
        localName: 'Search',
        propertyInfos: [{
            name: 'meta',
            minOccurs: 0,
            collection: true,
            elementName: 'Meta',
            typeInfo: '.AnyContent'
          }, {
            name: 'type',
            elementName: 'Type'
          }, {
            name: 'id',
            elementName: 'Id'
          }, {
            name: 'name',
            elementName: 'Name'
          }, {
            name: 'description',
            elementName: 'Description'
          }, {
            name: 'classification',
            elementName: 'Classification',
            typeInfo: '.Classification'
          }, {
            name: 'state',
            elementName: 'State'
          }, {
            name: 'groups',
            elementName: 'Groups',
            typeInfo: '.Groups'
          }, {
            name: 'permissions',
            elementName: 'Permissions',
            typeInfo: '.BaseObject.Permissions'
          }, {
            name: 'tags',
            elementName: 'Tags',
            typeInfo: '.MetaDataTags'
          }, {
            name: 'dataSources',
            elementName: 'DataSources',
            typeInfo: '.SearchResults.DataSources'
          }, {
            name: 'query',
            elementName: 'Query',
            typeInfo: '.Query'
          }, {
            name: 'resultPage',
            elementName: 'ResultPage',
            typeInfo: '.SearchResults.ResultPage'
          }, {
            name: 'totalResults',
            elementName: 'TotalResults',
            typeInfo: 'NonNegativeInteger'
          }, {
            name: 'results',
            elementName: 'Results',
            typeInfo: '.MultiObject'
          }, {
            name: 'outcome',
            elementName: 'Outcome',
            typeInfo: '.Outcome'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Resource',
        baseTypeInfo: '.BaseObject',
        propertyInfos: [{
            name: 'title',
            elementName: 'Title'
          }, {
            name: 'url',
            elementName: 'URL'
          }, {
            name: 'referrer',
            elementName: 'Referrer'
          }, {
            name: 'sessionId',
            elementName: 'SessionId'
          }, {
            name: 'httpMethod',
            elementName: 'HTTPMethod'
          }, {
            name: 'httpVersion',
            elementName: 'HTTPVersion'
          }, {
            name: 'userAgent',
            elementName: 'UserAgent'
          }, {
            name: 'inboundSize',
            elementName: 'InboundSize',
            typeInfo: 'NonNegativeInteger'
          }, {
            name: 'inboundContentSize',
            elementName: 'InboundContentSize',
            typeInfo: 'NonNegativeInteger'
          }, {
            name: 'inboundHeader',
            elementName: 'InboundHeader'
          }, {
            name: 'outboundSize',
            elementName: 'OutboundSize',
            typeInfo: 'NonNegativeInteger'
          }, {
            name: 'outboundContentSize',
            elementName: 'OutboundContentSize',
            typeInfo: 'NonNegativeInteger'
          }, {
            name: 'outboundHeader',
            elementName: 'OutboundHeader'
          }, {
            name: 'requestTime',
            elementName: 'RequestTime',
            typeInfo: 'NonNegativeInteger'
          }, {
            name: 'connectionStatus',
            elementName: 'ConnectionStatus'
          }, {
            name: 'initialResponseCode',
            elementName: 'InitialResponseCode'
          }, {
            name: 'responseCode',
            elementName: 'ResponseCode'
          }, {
            name: 'mimeType',
            elementName: 'MimeType'
          }, {
            name: 'category',
            elementName: 'Category'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Uninstall',
        propertyInfos: [{
            name: 'software',
            required: true,
            elementName: 'Software',
            typeInfo: '.Software'
          }, {
            name: 'hardware',
            required: true,
            elementName: 'Hardware',
            typeInfo: '.Hardware'
          }, {
            name: 'media',
            required: true,
            elementName: 'Media',
            typeInfo: '.Media'
          }, {
            name: 'outcome',
            elementName: 'Outcome',
            typeInfo: '.Outcome'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'BaseObject.Permissions',
        typeName: null,
        propertyInfos: [{
            name: 'permission',
            required: true,
            collection: true,
            elementName: 'Permission',
            typeInfo: '.BaseObject.Permissions.Permission'
          }]
      }, {
        localName: 'Process',
        propertyInfos: [{
            name: 'action',
            required: true,
            elementName: 'Action',
            typeInfo: '.ProcessAction'
          }, {
            name: 'type',
            required: true,
            elementName: 'Type',
            typeInfo: '.ProcessType'
          }, {
            name: 'command',
            required: true,
            elementName: 'Command'
          }, {
            name: 'arguments',
            elementName: 'Arguments'
          }, {
            name: 'processId',
            elementName: 'ProcessId'
          }, {
            name: 'threadId',
            elementName: 'ThreadId',
            typeInfo: 'PositiveInteger'
          }, {
            name: 'rule',
            elementName: 'Rule'
          }, {
            name: 'input',
            elementName: 'Input',
            typeInfo: '.MultiObject'
          }, {
            name: 'output',
            elementName: 'Output',
            typeInfo: '.MultiObject'
          }, {
            name: 'outcome',
            elementName: 'Outcome',
            typeInfo: '.Outcome'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Classification.Descriptors',
        typeName: null,
        propertyInfos: [{
            name: 'descriptor',
            required: true,
            collection: true,
            elementName: 'Descriptor'
          }]
      }, {
        localName: 'System.Tags',
        typeName: null,
        propertyInfos: [{
            name: 'tag',
            required: true,
            collection: true,
            elementName: 'Tag'
          }]
      }, {
        localName: 'BaseObjectOutcome',
        propertyInfos: [{
            name: 'multiObjectGroup',
            required: true,
            collection: true,
            elementTypeInfos: [{
                elementName: 'Association',
                typeInfo: '.Association'
              }, {
                elementName: 'Banner',
                typeInfo: '.Banner'
              }, {
                elementName: 'Chat',
                typeInfo: '.Chat'
              }, {
                elementName: 'Configuration',
                typeInfo: '.Configuration'
              }, {
                elementName: 'Criteria',
                typeInfo: '.Criteria'
              }, {
                elementName: 'Document',
                typeInfo: '.Document'
              }, {
                elementName: 'Email',
                typeInfo: '.Email'
              }, {
                elementName: 'File',
                typeInfo: '.File'
              }, {
                elementName: 'Folder',
                typeInfo: '.Folder'
              }, {
                elementName: 'Group',
                typeInfo: '.Group'
              }, {
                elementName: 'GroupChat',
                typeInfo: '.GroupChat'
              }, {
                elementName: 'Object',
                typeInfo: '.Object'
              }, {
                elementName: 'SearchResults',
                typeInfo: '.SearchResults'
              }, {
                elementName: 'Shortcut',
                typeInfo: '.Shortcut'
              }, {
                elementName: 'User',
                typeInfo: '.User'
              }, {
                elementName: 'VirtualSession',
                typeInfo: '.VirtualSession'
              }, {
                elementName: 'VOIP',
                typeInfo: '.VOIP'
              }, {
                elementName: 'Resource',
                typeInfo: '.Resource'
              }],
            type: 'elements'
          }, {
            name: 'outcome',
            elementName: 'Outcome',
            typeInfo: '.Outcome'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'BaseNetwork',
        propertyInfos: [{
            name: 'source',
            required: true,
            elementName: 'Source',
            typeInfo: '.NetworkLocation'
          }, {
            name: 'destination',
            elementName: 'Destination',
            typeInfo: '.NetworkLocation'
          }, {
            name: 'processName',
            elementName: 'ProcessName'
          }, {
            name: 'payload',
            elementName: 'Payload',
            typeInfo: '.MultiObject'
          }, {
            name: 'rule',
            elementName: 'Rule'
          }]
      }, {
        localName: 'Group',
        baseTypeInfo: '.BaseObject',
        propertyInfos: [{
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'System',
        propertyInfos: [{
            name: 'name',
            required: true,
            elementName: 'Name'
          }, {
            name: 'description',
            elementName: 'Description'
          }, {
            name: 'classification',
            elementName: 'Classification',
            typeInfo: '.Classification'
          }, {
            name: 'environment',
            required: true,
            elementName: 'Environment'
          }, {
            name: 'organisation',
            elementName: 'Organisation'
          }, {
            name: 'version',
            elementName: 'Version'
          }, {
            name: 'tags',
            elementName: 'Tags',
            typeInfo: '.System.Tags'
          }]
      }, {
        localName: 'User',
        baseTypeInfo: '.BaseObject',
        propertyInfos: [{
            name: 'domain',
            elementName: 'Domain'
          }, {
            name: 'emailAddress',
            elementName: 'EmailAddress'
          }, {
            name: 'userDetails',
            elementName: 'UserDetails',
            typeInfo: '.UserDetails'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Groups',
        propertyInfos: [{
            name: 'group',
            minOccurs: 0,
            collection: true,
            elementName: 'Group',
            typeInfo: '.Group'
          }]
      }, {
        localName: 'Folder',
        baseTypeInfo: '.BaseFile'
      }, {
        localName: 'Export',
        propertyInfos: [{
            name: 'source',
            elementName: 'Source',
            typeInfo: '.MultiObject'
          }, {
            name: 'destination',
            elementName: 'Destination',
            typeInfo: '.MultiObject'
          }, {
            name: 'outcome',
            elementName: 'Outcome',
            typeInfo: '.Outcome'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Query.Advanced',
        typeName: null,
        propertyInfos: [{
            name: 'advancedQueryOperatorGroup',
            minOccurs: 0,
            collection: true,
            elementTypeInfos: [{
                elementName: 'Term',
                typeInfo: '.Term'
              }, {
                elementName: 'And',
                typeInfo: '.And'
              }, {
                elementName: 'Or',
                typeInfo: '.Or'
              }, {
                elementName: 'Not',
                typeInfo: '.Not'
              }],
            type: 'elements'
          }]
      }, {
        localName: 'Authorise.AddGroups',
        typeName: null,
        propertyInfos: [{
            name: 'group',
            minOccurs: 0,
            collection: true,
            elementName: 'Group',
            typeInfo: '.Group'
          }]
      }, {
        localName: 'AntiMalwareThreat',
        propertyInfos: [{
            name: 'product',
            elementName: 'Product',
            typeInfo: '.Software'
          }, {
            name: 'signature',
            elementName: 'Signature',
            typeInfo: '.AntiMalwareThreat.Signature'
          }, {
            name: 'threat',
            elementName: 'Threat',
            typeInfo: '.AntiMalwareThreat.Threat'
          }, {
            name: 'infected',
            elementName: 'Infected',
            typeInfo: '.MultiObject'
          }]
      }, {
        localName: 'Authenticate',
        propertyInfos: [{
            name: 'action',
            required: true,
            elementName: 'Action',
            typeInfo: '.AuthenticateAction'
          }, {
            name: 'logonType',
            elementName: 'LogonType',
            typeInfo: '.AuthenticateLogonType'
          }, {
            name: 'user',
            required: true,
            elementName: 'User',
            typeInfo: '.User'
          }, {
            name: 'device',
            required: true,
            elementName: 'Device',
            typeInfo: '.Device'
          }, {
            name: 'group',
            required: true,
            elementName: 'Group',
            typeInfo: '.Group'
          }, {
            name: 'outcome',
            elementName: 'Outcome',
            typeInfo: '.AuthenticateOutcome'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'SearchResults.ResultPage',
        typeName: null,
        propertyInfos: [{
            name: 'totalPages',
            elementName: 'TotalPages',
            typeInfo: 'NonNegativeInteger'
          }, {
            name: 'perPage',
            elementName: 'PerPage',
            typeInfo: 'NonNegativeInteger'
          }, {
            name: 'pageNumber',
            elementName: 'PageNumber',
            typeInfo: 'NonNegativeInteger'
          }, {
            name: 'from',
            elementName: 'From',
            typeInfo: 'NonNegativeInteger'
          }, {
            name: 'to',
            elementName: 'To',
            typeInfo: 'NonNegativeInteger'
          }]
      }, {
        localName: 'Document',
        baseTypeInfo: '.BaseObject',
        propertyInfos: [{
            name: 'title',
            elementName: 'Title'
          }, {
            name: 'reference',
            elementName: 'Reference'
          }, {
            name: 'version',
            elementName: 'Version'
          }, {
            name: 'path',
            elementName: 'Path'
          }, {
            name: 'created',
            elementName: 'Created',
            typeInfo: 'DateTime'
          }, {
            name: 'modified',
            elementName: 'Modified',
            typeInfo: 'DateTime'
          }, {
            name: 'accessed',
            elementName: 'Accessed',
            typeInfo: 'DateTime'
          }, {
            name: 'pages',
            elementName: 'Pages',
            typeInfo: 'NonNegativeInteger'
          }, {
            name: 'size',
            elementName: 'Size',
            typeInfo: 'NonNegativeInteger'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Data',
        propertyInfos: [{
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }, {
            name: 'name',
            required: true,
            attributeName: {
              localPart: 'Name'
            },
            type: 'attribute'
          }, {
            name: 'value',
            attributeName: {
              localPart: 'Value'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'Send.Source',
        typeName: null,
        propertyInfos: [{
            name: 'userOrDevice',
            required: true,
            collection: true,
            elementTypeInfos: [{
                elementName: 'User',
                typeInfo: '.User'
              }, {
                elementName: 'Device',
                typeInfo: '.Device'
              }],
            type: 'elements'
          }]
      }, {
        localName: 'Classification.DisseminationControls',
        typeName: null,
        propertyInfos: [{
            name: 'disseminationControl',
            required: true,
            collection: true,
            elementName: 'DisseminationControl'
          }]
      }, {
        localName: 'Import',
        propertyInfos: [{
            name: 'source',
            elementName: 'Source',
            typeInfo: '.MultiObject'
          }, {
            name: 'destination',
            elementName: 'Destination',
            typeInfo: '.MultiObject'
          }, {
            name: 'outcome',
            elementName: 'Outcome',
            typeInfo: '.Outcome'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Approval.Approvers',
        typeName: null,
        propertyInfos: [{
            name: 'approver',
            required: true,
            collection: true,
            elementName: 'Approver',
            typeInfo: '.User'
          }]
      }, {
        localName: 'BaseObject.Permissions.Permission',
        typeName: null,
        propertyInfos: [{
            name: 'user',
            required: true,
            elementName: 'User',
            typeInfo: '.User'
          }, {
            name: 'group',
            required: true,
            elementName: 'Group',
            typeInfo: '.Group'
          }, {
            name: 'allow',
            minOccurs: 0,
            collection: true,
            elementName: 'Allow',
            typeInfo: '.PermissionAttribute'
          }, {
            name: 'deny',
            minOccurs: 0,
            collection: true,
            elementName: 'Deny',
            typeInfo: '.PermissionAttribute'
          }]
      }, {
        localName: 'Query',
        propertyInfos: [{
            name: 'id',
            elementName: 'Id'
          }, {
            name: 'name',
            elementName: 'Name'
          }, {
            name: 'description',
            elementName: 'Description'
          }, {
            name: 'advanced',
            elementName: 'Advanced',
            typeInfo: '.Query.Advanced'
          }, {
            name: 'simple',
            elementName: 'Simple',
            typeInfo: '.Query.Simple'
          }, {
            name: 'raw',
            elementName: 'Raw'
          }]
      }, {
        localName: 'EventDetail',
        propertyInfos: [{
            name: 'typeId',
            required: true,
            elementName: 'TypeId'
          }, {
            name: 'description',
            elementName: 'Description'
          }, {
            name: 'purpose',
            elementName: 'Purpose',
            typeInfo: '.Purpose'
          }, {
            name: 'authenticate',
            required: true,
            elementName: 'Authenticate',
            typeInfo: '.Authenticate'
          }, {
            name: 'authorise',
            required: true,
            elementName: 'Authorise',
            typeInfo: '.Authorise'
          }, {
            name: 'search',
            required: true,
            elementName: 'Search',
            typeInfo: '.Search'
          }, {
            name: 'copy',
            required: true,
            elementName: 'Copy',
            typeInfo: '.Copy'
          }, {
            name: 'move',
            required: true,
            elementName: 'Move',
            typeInfo: '.Move'
          }, {
            name: 'create',
            required: true,
            elementName: 'Create',
            typeInfo: '.Create'
          }, {
            name: 'view',
            required: true,
            elementName: 'View',
            typeInfo: '.View'
          }, {
            name: '_import',
            required: true,
            elementName: 'Import',
            typeInfo: '.Import'
          }, {
            name: 'export',
            required: true,
            elementName: 'Export',
            typeInfo: '.Export'
          }, {
            name: 'update',
            required: true,
            elementName: 'Update',
            typeInfo: '.Update'
          }, {
            name: 'delete',
            required: true,
            elementName: 'Delete',
            typeInfo: '.Delete'
          }, {
            name: 'process',
            required: true,
            elementName: 'Process',
            typeInfo: '.Process'
          }, {
            name: 'print',
            required: true,
            elementName: 'Print',
            typeInfo: '.Print'
          }, {
            name: 'install',
            required: true,
            elementName: 'Install',
            typeInfo: '.Install'
          }, {
            name: 'uninstall',
            required: true,
            elementName: 'Uninstall',
            typeInfo: '.Uninstall'
          }, {
            name: 'network',
            required: true,
            elementName: 'Network',
            typeInfo: '.NetworkEventAction'
          }, {
            name: 'alert',
            required: true,
            elementName: 'Alert',
            typeInfo: '.Alert'
          }, {
            name: 'send',
            required: true,
            elementName: 'Send',
            typeInfo: '.Send'
          }, {
            name: 'receive',
            required: true,
            elementName: 'Receive',
            typeInfo: '.Receive'
          }, {
            name: 'approval',
            required: true,
            elementName: 'Approval',
            typeInfo: '.Approval'
          }, {
            name: 'unknown',
            required: true,
            elementName: 'Unknown',
            typeInfo: '.EventDetail.Unknown'
          }]
      }, {
        localName: 'Copy',
        propertyInfos: [{
            name: 'source',
            required: true,
            elementName: 'Source',
            typeInfo: '.MultiObject'
          }, {
            name: 'destination',
            required: true,
            elementName: 'Destination',
            typeInfo: '.MultiObject'
          }, {
            name: 'outcome',
            elementName: 'Outcome',
            typeInfo: '.CopyMoveOutcome'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'NetworkOutcome',
        baseTypeInfo: '.BaseNetwork',
        propertyInfos: [{
            name: 'outcome',
            elementName: 'Outcome',
            typeInfo: '.Outcome'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Chat',
        baseTypeInfo: '.BaseChat'
      }, {
        localName: 'EventTime',
        propertyInfos: [{
            name: 'timeCreated',
            required: true,
            elementName: 'TimeCreated',
            typeInfo: 'DateTime'
          }, {
            name: 'timeSource',
            elementName: 'TimeSource',
            typeInfo: '.Device'
          }]
      }, {
        localName: 'EventSource.Door.AddAccess',
        typeName: null,
        propertyInfos: [{
            name: 'accessZone',
            required: true,
            collection: true,
            elementName: 'AccessZone'
          }]
      }, {
        localName: 'Print.PrintJob',
        typeName: null,
        propertyInfos: [{
            name: 'document',
            required: true,
            elementName: 'Document',
            typeInfo: '.Document'
          }, {
            name: 'pages',
            elementName: 'Pages',
            typeInfo: 'NonNegativeInteger'
          }, {
            name: 'size',
            elementName: 'Size',
            typeInfo: 'NonNegativeInteger'
          }, {
            name: 'submitted',
            elementName: 'Submitted',
            typeInfo: 'DateTime'
          }]
      }, {
        localName: 'BaseChat',
        baseTypeInfo: '.BaseObject',
        propertyInfos: [{
            name: 'sessionId',
            elementName: 'SessionId'
          }, {
            name: 'room',
            elementName: 'Room'
          }, {
            name: 'from',
            elementName: 'From',
            typeInfo: '.User'
          }, {
            name: 'to',
            minOccurs: 0,
            collection: true,
            elementName: 'To',
            typeInfo: '.User'
          }, {
            name: 'content',
            elementName: 'Content'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Shortcut',
        baseTypeInfo: '.BaseFile'
      }, {
        localName: 'NetworkLocation',
        propertyInfos: [{
            name: 'device',
            elementName: 'Device',
            typeInfo: '.Device'
          }, {
            name: 'application',
            elementName: 'Application'
          }, {
            name: 'transportProtocol',
            elementName: 'TransportProtocol',
            typeInfo: '.NetworkProtocol'
          }, {
            name: 'icmpType',
            elementName: 'ICMPType',
            typeInfo: 'Integer'
          }, {
            name: 'httpMethod',
            elementName: 'HTTPMethod'
          }, {
            name: 'applicationProtocol',
            elementName: 'ApplicationProtocol'
          }, {
            name: 'port',
            elementName: 'Port',
            typeInfo: 'Int'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Not',
        propertyInfos: [{
            name: 'advancedQueryOperatorGroup',
            minOccurs: 0,
            collection: true,
            elementTypeInfos: [{
                elementName: 'Term',
                typeInfo: '.Term'
              }, {
                elementName: 'And',
                typeInfo: '.And'
              }, {
                elementName: 'Or',
                typeInfo: '.Or'
              }, {
                elementName: 'Not',
                typeInfo: '.Not'
              }],
            type: 'elements'
          }]
      }, {
        localName: 'EventSource.Door',
        typeName: null,
        propertyInfos: [{
            name: 'name',
            required: true,
            elementName: 'Name'
          }, {
            name: 'description',
            elementName: 'Description'
          }, {
            name: 'location',
            required: true,
            elementName: 'Location',
            typeInfo: '.Location'
          }, {
            name: 'singleEntry',
            elementName: 'SingleEntry',
            typeInfo: 'Boolean'
          }, {
            name: 'removeAll',
            elementName: 'RemoveAll',
            typeInfo: 'Boolean'
          }, {
            name: 'addAccess',
            required: true,
            elementName: 'AddAccess',
            typeInfo: '.EventSource.Door.AddAccess'
          }]
      }, {
        localName: 'Send',
        propertyInfos: [{
            name: 'source',
            required: true,
            elementName: 'Source',
            typeInfo: '.Send.Source'
          }, {
            name: 'destination',
            required: true,
            elementName: 'Destination',
            typeInfo: '.Send.Destination'
          }, {
            name: 'payload',
            elementName: 'Payload',
            typeInfo: '.MultiObject'
          }, {
            name: 'outcome',
            elementName: 'Outcome',
            typeInfo: '.Outcome'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'EventChain',
        propertyInfos: [{
            name: 'activity',
            required: true,
            elementName: 'Activity',
            typeInfo: '.Activity'
          }]
      }, {
        localName: 'EventSource',
        propertyInfos: [{
            name: 'eventId',
            elementName: 'EventId'
          }, {
            name: 'sessionId',
            elementName: 'SessionId'
          }, {
            name: 'system',
            required: true,
            elementName: 'System',
            typeInfo: '.System'
          }, {
            name: 'generator',
            required: true,
            elementName: 'Generator'
          }, {
            name: 'device',
            required: true,
            elementName: 'Device',
            typeInfo: '.Device'
          }, {
            name: 'client',
            elementName: 'Client',
            typeInfo: '.Device'
          }, {
            name: 'server',
            elementName: 'Server',
            typeInfo: '.Device'
          }, {
            name: 'door',
            elementName: 'Door',
            typeInfo: '.EventSource.Door'
          }, {
            name: 'user',
            elementName: 'User',
            typeInfo: '.User'
          }, {
            name: 'runAs',
            elementName: 'RunAs',
            typeInfo: '.User'
          }, {
            name: 'interactive',
            elementName: 'Interactive',
            typeInfo: 'Boolean'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'EventDetail.Unknown',
        typeName: null,
        propertyInfos: [{
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'AccessControlGroups',
        propertyInfos: [{
            name: 'accessControlGroup',
            required: true,
            collection: true,
            elementName: 'AccessControlGroup'
          }]
      }, {
        localName: 'VirtualSession',
        baseTypeInfo: '.BaseObject',
        propertyInfos: [{
            name: 'sessionState',
            elementName: 'SessionState',
            typeInfo: '.VirtualSessionSessionState'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Device',
        propertyInfos: [{
            name: 'id',
            elementName: 'Id'
          }, {
            name: 'name',
            elementName: 'Name'
          }, {
            name: 'classification',
            elementName: 'Classification',
            typeInfo: '.Classification'
          }, {
            name: 'hostName',
            elementName: 'HostName'
          }, {
            name: 'ipAddress',
            elementName: 'IPAddress'
          }, {
            name: 'macAddress',
            elementName: 'MACAddress'
          }, {
            name: 'port',
            elementName: 'Port',
            typeInfo: 'Int'
          }, {
            name: 'location',
            elementName: 'Location',
            typeInfo: '.Location'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'UserDetails'
      }, {
        localName: 'SearchResults.DataSources',
        typeName: null,
        propertyInfos: [{
            name: 'dataSource',
            required: true,
            collection: true,
            elementName: 'DataSource'
          }]
      }, {
        localName: 'VOIP',
        baseTypeInfo: '.BaseObject',
        propertyInfos: [{
            name: 'phoneNumber',
            elementName: 'PhoneNumber'
          }, {
            name: 'from',
            elementName: 'From',
            typeInfo: '.User'
          }, {
            name: 'to',
            minOccurs: 0,
            collection: true,
            elementName: 'To',
            typeInfo: '.User'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Banner',
        baseTypeInfo: '.BaseObject',
        propertyInfos: [{
            name: 'version',
            elementName: 'Version'
          }, {
            name: 'message',
            elementName: 'Message'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'File',
        baseTypeInfo: '.BaseFile'
      }, {
        localName: 'Object',
        baseTypeInfo: '.BaseObject',
        propertyInfos: [{
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Print.PrintSettings',
        typeName: null,
        propertyInfos: [{
            name: 'paperSize',
            elementName: 'PaperSize'
          }, {
            name: 'orientation',
            elementName: 'Orientation',
            typeInfo: '.PrintSettingsOrientation'
          }, {
            name: 'colour',
            elementName: 'Colour',
            typeInfo: 'Boolean'
          }, {
            name: 'deviceFonts',
            elementName: 'DeviceFonts',
            typeInfo: 'Boolean'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Events',
        typeName: null,
        propertyInfos: [{
            name: 'event',
            minOccurs: 0,
            collection: true,
            elementName: 'Event',
            typeInfo: '.Event'
          }, {
            name: 'version',
            required: true,
            values: ['4.0-beta.3'],
            attributeName: {
              localPart: 'Version'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'Alert',
        propertyInfos: [{
            name: 'type',
            required: true,
            elementName: 'Type',
            typeInfo: '.AlertType'
          }, {
            name: 'severity',
            elementName: 'Severity',
            typeInfo: '.AlertSeverity'
          }, {
            name: 'priority',
            elementName: 'Priority',
            typeInfo: '.AlertPriority'
          }, {
            name: 'subject',
            elementName: 'Subject'
          }, {
            name: 'description',
            elementName: 'Description'
          }, {
            name: 'ids',
            elementName: 'IDS',
            typeInfo: '.Alert.IDS'
          }, {
            name: 'malware',
            elementName: 'Malware',
            typeInfo: '.AntiMalwareThreat'
          }, {
            name: 'network',
            elementName: 'Network',
            typeInfo: '.Network'
          }, {
            name: 'change',
            elementName: 'Change',
            typeInfo: '.Alert.Change'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Purpose',
        propertyInfos: [{
            name: 'classification',
            elementName: 'Classification',
            typeInfo: '.Classification'
          }, {
            name: 'subject',
            elementName: 'Subject'
          }, {
            name: 'stakeholders',
            elementName: 'Stakeholders'
          }, {
            name: 'justification',
            elementName: 'Justification'
          }, {
            name: 'expectedOutcome',
            elementName: 'ExpectedOutcome'
          }, {
            name: 'authorisations',
            elementName: 'Authorisations',
            typeInfo: '.Purpose.Authorisations'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Send.Destination',
        typeName: null,
        propertyInfos: [{
            name: 'userOrDevice',
            required: true,
            collection: true,
            elementTypeInfos: [{
                elementName: 'User',
                typeInfo: '.User'
              }, {
                elementName: 'Device',
                typeInfo: '.Device'
              }],
            type: 'elements'
          }]
      }, {
        localName: 'Update',
        propertyInfos: [{
            name: 'before',
            elementName: 'Before',
            typeInfo: '.MultiObject'
          }, {
            name: 'after',
            required: true,
            elementName: 'After',
            typeInfo: '.MultiObject'
          }, {
            name: 'outcome',
            elementName: 'Outcome',
            typeInfo: '.Outcome'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Authorise',
        propertyInfos: [{
            name: 'multiObjectGroup',
            required: true,
            collection: true,
            elementTypeInfos: [{
                elementName: 'Association',
                typeInfo: '.Association'
              }, {
                elementName: 'Banner',
                typeInfo: '.Banner'
              }, {
                elementName: 'Chat',
                typeInfo: '.Chat'
              }, {
                elementName: 'Configuration',
                typeInfo: '.Configuration'
              }, {
                elementName: 'Criteria',
                typeInfo: '.Criteria'
              }, {
                elementName: 'Document',
                typeInfo: '.Document'
              }, {
                elementName: 'Email',
                typeInfo: '.Email'
              }, {
                elementName: 'File',
                typeInfo: '.File'
              }, {
                elementName: 'Folder',
                typeInfo: '.Folder'
              }, {
                elementName: 'Group',
                typeInfo: '.Group'
              }, {
                elementName: 'GroupChat',
                typeInfo: '.GroupChat'
              }, {
                elementName: 'Object',
                typeInfo: '.Object'
              }, {
                elementName: 'SearchResults',
                typeInfo: '.SearchResults'
              }, {
                elementName: 'Shortcut',
                typeInfo: '.Shortcut'
              }, {
                elementName: 'User',
                typeInfo: '.User'
              }, {
                elementName: 'VirtualSession',
                typeInfo: '.VirtualSession'
              }, {
                elementName: 'VOIP',
                typeInfo: '.VOIP'
              }, {
                elementName: 'Resource',
                typeInfo: '.Resource'
              }],
            type: 'elements'
          }, {
            name: 'action',
            elementName: 'Action',
            typeInfo: '.Authorisation'
          }, {
            name: 'addGroups',
            elementName: 'AddGroups',
            typeInfo: '.Authorise.AddGroups'
          }, {
            name: 'removeGroups',
            elementName: 'RemoveGroups',
            typeInfo: '.Authorise.RemoveGroups'
          }, {
            name: 'outcome',
            elementName: 'Outcome',
            typeInfo: '.Outcome'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Organisation',
        propertyInfos: [{
            name: 'country',
            elementName: 'Country'
          }, {
            name: 'organisation',
            required: true,
            elementName: 'Organisation'
          }]
      }, {
        localName: 'Purpose.Authorisations',
        typeName: null,
        propertyInfos: [{
            name: 'auth',
            required: true,
            collection: true,
            elementName: 'Auth',
            typeInfo: '.Purpose.Authorisations.Auth'
          }]
      }, {
        localName: 'Association',
        baseTypeInfo: '.BaseObject',
        propertyInfos: [{
            name: 'objects',
            required: true,
            elementName: 'Objects',
            typeInfo: '.MultiObject'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Alert.IDS',
        typeName: null,
        propertyInfos: [{
            name: 'rule',
            elementName: 'Rule'
          }, {
            name: 'source',
            elementName: 'Source',
            typeInfo: '.NetworkLocation'
          }, {
            name: 'destination',
            elementName: 'Destination',
            typeInfo: '.NetworkLocation'
          }, {
            name: 'payload',
            elementName: 'Payload',
            typeInfo: '.MultiObject'
          }]
      }, {
        localName: 'Receive',
        propertyInfos: [{
            name: 'source',
            required: true,
            elementName: 'Source',
            typeInfo: '.Send.Source'
          }, {
            name: 'destination',
            required: true,
            elementName: 'Destination',
            typeInfo: '.Send.Destination'
          }, {
            name: 'payload',
            elementName: 'Payload',
            typeInfo: '.MultiObject'
          }, {
            name: 'outcome',
            elementName: 'Outcome',
            typeInfo: '.Outcome'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Coordinates',
        propertyInfos: [{
            name: 'latitude',
            required: true,
            elementName: 'Latitude',
            typeInfo: 'Decimal'
          }, {
            name: 'longitude',
            required: true,
            elementName: 'Longitude',
            typeInfo: 'Decimal'
          }]
      }, {
        localName: 'Outcome',
        baseTypeInfo: '.BaseOutcome',
        propertyInfos: [{
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'AntiMalwareThreat.Threat',
        typeName: null,
        propertyInfos: [{
            name: 'category',
            required: true,
            elementName: 'Category',
            typeInfo: '.ThreatCategory'
          }, {
            name: 'name',
            required: true,
            elementName: 'Name'
          }]
      }, {
        localName: 'Software',
        propertyInfos: [{
            name: 'id',
            elementName: 'Id'
          }, {
            name: 'name',
            required: true,
            elementName: 'Name'
          }, {
            name: 'version',
            elementName: 'Version'
          }, {
            name: 'manufacturer',
            elementName: 'Manufacturer'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Media',
        propertyInfos: [{
            name: 'type',
            required: true,
            elementName: 'Type',
            typeInfo: '.MediaType'
          }, {
            name: 'id',
            elementName: 'Id'
          }, {
            name: 'name',
            elementName: 'Name'
          }, {
            name: 'removable',
            elementName: 'Removable',
            typeInfo: 'Boolean'
          }, {
            name: 'readWrite',
            elementName: 'ReadWrite',
            typeInfo: 'Boolean'
          }, {
            name: 'capacity',
            elementName: 'Capacity',
            typeInfo: 'PositiveInteger'
          }, {
            name: 'classification',
            elementName: 'Classification',
            typeInfo: '.Classification'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'SearchResults',
        baseTypeInfo: '.BaseObject',
        propertyInfos: [{
            name: 'dataSources',
            elementName: 'DataSources',
            typeInfo: '.SearchResults.DataSources'
          }, {
            name: 'query',
            elementName: 'Query',
            typeInfo: '.Query'
          }, {
            name: 'resultPage',
            elementName: 'ResultPage',
            typeInfo: '.SearchResults.ResultPage'
          }, {
            name: 'totalResults',
            elementName: 'TotalResults',
            typeInfo: 'NonNegativeInteger'
          }, {
            name: 'results',
            elementName: 'Results',
            typeInfo: '.MultiObject'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Classification.Disposition',
        typeName: null,
        propertyInfos: [{
            name: 'date',
            required: true,
            elementName: 'Date',
            typeInfo: 'DateTime'
          }, {
            name: 'process',
            required: true,
            elementName: 'Process'
          }]
      }, {
        localName: 'Print',
        propertyInfos: [{
            name: 'action',
            required: true,
            elementName: 'Action',
            typeInfo: '.PrintAction'
          }, {
            name: 'printJob',
            required: true,
            elementName: 'PrintJob',
            typeInfo: '.Print.PrintJob'
          }, {
            name: 'printSettings',
            elementName: 'PrintSettings',
            typeInfo: '.Print.PrintSettings'
          }, {
            name: 'printer',
            elementName: 'Printer',
            typeInfo: '.Device'
          }, {
            name: 'outcome',
            elementName: 'Outcome',
            typeInfo: '.Outcome'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'AnyContent',
        propertyInfos: [{
            name: 'content',
            collection: true,
            type: 'anyElement'
          }, {
            name: 'contentType',
            attributeName: {
              localPart: 'ContentType'
            },
            type: 'attribute'
          }, {
            name: 'version',
            attributeName: {
              localPart: 'Version'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CopyMoveOutcome',
        baseTypeInfo: '.BaseOutcome',
        propertyInfos: [{
            name: 'reason',
            elementName: 'Reason',
            typeInfo: '.CopyMoveOutcomeReason'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        localName: 'Purpose.Authorisations.Auth',
        typeName: null,
        propertyInfos: [{
            name: 'refNo',
            elementName: 'RefNo'
          }, {
            name: 'detail',
            elementName: 'Detail'
          }]
      }, {
        localName: 'And',
        propertyInfos: [{
            name: 'advancedQueryOperatorGroup',
            minOccurs: 0,
            collection: true,
            elementTypeInfos: [{
                elementName: 'Term',
                typeInfo: '.Term'
              }, {
                elementName: 'And',
                typeInfo: '.And'
              }, {
                elementName: 'Or',
                typeInfo: '.Or'
              }, {
                elementName: 'Not',
                typeInfo: '.Not'
              }],
            type: 'elements'
          }]
      }, {
        localName: 'BaseFile',
        baseTypeInfo: '.BaseObject',
        propertyInfos: [{
            name: 'path',
            elementName: 'Path'
          }, {
            name: 'created',
            elementName: 'Created',
            typeInfo: 'DateTime'
          }, {
            name: 'modified',
            elementName: 'Modified',
            typeInfo: 'DateTime'
          }, {
            name: 'accessed',
            elementName: 'Accessed',
            typeInfo: 'DateTime'
          }, {
            name: 'size',
            elementName: 'Size',
            typeInfo: 'NonNegativeInteger'
          }, {
            name: 'media',
            elementName: 'Media',
            typeInfo: '.Media'
          }, {
            name: 'hash',
            elementName: 'Hash',
            typeInfo: '.Hash'
          }, {
            name: 'data',
            minOccurs: 0,
            collection: true,
            elementName: 'Data',
            typeInfo: '.Data'
          }]
      }, {
        type: 'enumInfo',
        localName: 'TermCondition',
        values: ['Exists', 'NotExists', 'Contains', 'NotContains', 'Empty', 'NotEmpty', 'Equals', 'NotEquals', 'GreaterThan', 'GreaterThanEqualTo', 'LessThan', 'LessThanEqualTo', 'StartsWith', 'NotStartsWith', 'Regex', 'NotRegex']
      }, {
        type: 'enumInfo',
        localName: 'AlertPriority',
        values: ['None', 'Low', 'Normal', 'High', 'Urgent', 'Immediate']
      }, {
        type: 'enumInfo',
        localName: 'ChangeAction',
        values: ['StartScan', 'StopScan', 'FileAdded', 'FileRemoved', 'FileModified']
      }, {
        type: 'enumInfo',
        localName: 'AlertType',
        values: ['Vulnerability', 'IDS', 'Malware', 'Network', 'Change', 'Error', 'Other']
      }, {
        type: 'enumInfo',
        localName: 'AlertSeverity',
        values: ['Info', 'Minor', 'Major', 'Critical']
      }, {
        type: 'enumInfo',
        localName: 'Authorisation',
        values: ['Request', 'Modify']
      }, {
        type: 'enumInfo',
        localName: 'PrintAction',
        values: ['CreateJob', 'CancelJob', 'PauseJob', 'ResumeJob', 'StartPrint', 'FinishPrint', 'CancelPrint', 'FailedPrint', 'Other']
      }, {
        type: 'enumInfo',
        localName: 'AuthenticateOutcomeReason',
        values: ['IncorrectUsernameOrPassword', 'IncorrectUsername', 'IncorrectPassword', 'ExpiredCertificate', 'RevokedCertificate', 'IncorrectCA', 'ExpiredCA', 'AccountLocked', 'AccountNotValidForLoginType', 'Other']
      }, {
        type: 'enumInfo',
        localName: 'CopyMoveOutcomeReason',
        values: ['DeviceFull', 'IOError', 'InvalidPath', 'PermissionDenied', 'ReadOnly']
      }, {
        type: 'enumInfo',
        localName: 'ProcessAction',
        values: ['Startup', 'Shutdown', 'Execute', 'Terminate', 'ChangeDir', 'Call', 'Access', 'RequestObjectHandle', 'Register']
      }, {
        type: 'enumInfo',
        localName: 'AuthenticateAction',
        values: ['Logon', 'Logoff', 'ChangePassword', 'ResetPassword', 'ScreenLock', 'ScreenUnlock', 'AccountLock', 'AccountUnlock', 'Reconnect', 'Disconnect', 'Connect', 'ElevatePrivilege', 'ReadToken', 'Other']
      }, {
        type: 'enumInfo',
        localName: 'ProcessType',
        values: ['OS', 'Service', 'Application']
      }, {
        type: 'enumInfo',
        localName: 'AuthenticateLogonType',
        values: ['Interactive', 'Network', 'Batch', 'Service', 'Unlock', 'NetworkCleartext', 'NewCredentials', 'RemoteInteractive', 'CachedInteractive', 'CachedRemoteInteractive', 'CachedUnlock', 'Proxy', 'PhysicalAccess', 'Other']
      }, {
        type: 'enumInfo',
        localName: 'ApprovalAction',
        values: ['Approve', 'Accept', 'Reject', 'RequestApproval', 'Other']
      }, {
        type: 'enumInfo',
        localName: 'NetworkProtocol',
        values: ['TCP', 'UDP', 'ICMP', 'IGMP', 'Other']
      }, {
        type: 'enumInfo',
        localName: 'VirtualSessionSessionState',
        values: ['Parked', 'Unparked']
      }, {
        type: 'enumInfo',
        localName: 'PermissionAttribute',
        values: ['Author', 'Owner', 'Read', 'Write', 'Execute']
      }, {
        type: 'enumInfo',
        localName: 'MediaType',
        values: ['HardDisk', 'USBMassStorage', 'BluRay', 'DVD', 'CD', 'FloppyDisk', 'Tape', 'MemoryCard', 'Other']
      }, {
        type: 'enumInfo',
        localName: 'HardwareType',
        values: ['OpticalDrive', 'HardDisk', 'USBMassStorage', 'Printer', 'Modem', 'Keyboard', 'Mouse', 'Webcam', 'Other']
      }, {
        type: 'enumInfo',
        localName: 'ThreatCategory',
        values: ['Virus', 'Worm', 'HackingTool', 'Spyware', 'TrojanHorse', 'Adware', 'Other']
      }, {
        type: 'enumInfo',
        localName: 'PrintSettingsOrientation',
        values: ['Portrait', 'Landscape']
      }],
    elementInfos: [{
        typeInfo: '.Events',
        elementName: 'Events'
      }, {
        typeInfo: '.Event',
        elementName: 'Event'
      }]
  };
  return {
    event_logging: event_logging
  };
};
if (typeof define === 'function' && define.amd) {
  define([], event_logging_Module_Factory);
}
else {
  var event_logging_Module = event_logging_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.event_logging = event_logging_Module.event_logging;
  }
  else {
    var event_logging = event_logging_Module.event_logging;
  }
}